### ISSUE TITLE
Peer review #2 Paper 2

### ISSUE THREAD

**Issue by sarahhhh02** [RayanAlim/Birth_Rate_Analysis#4]
Firstly in your README, the LLM usage statement is there, but the location of it is not existent. You mention the chat history is available in 
>  inputs/llms/usage.txt

However, there is no path with inputs. Instead, I think you meant to say 

> other/llms/usage.txt"

Another thing in the README is the title you have put for it. The title should be descriptive and relevant to your topic of the paper. It should not just only read "Starter Folder" as it isn't a starter folder in the first place. 

Another thing is that there are no sketches found relevant to the research you are doing. You have the sketches that are given in the starter folder when downloaded, but non of your own. The rubric requires you to have one!

Upon looking at the paper, the first thing I noticed was the title. The title reads:

> Red States = Red Flags?∗
An analysis of birth rate trends from 2001 to 2019 and an exploration of political aﬀiliation of different states and Birth rates in the United States,

I feel as though "Red States = Red Flags?∗" isn't really appropriate as the title as it is not descriptive of the paper as a whole. Rather I feel the smaller fonts under, "An analysis of birth rate trends from 2001 to 2019 and an exploration of political aﬀiliation of different states and Birth rates in the United States," would fit as the better title. Also there should not be a comma at the end of this! 

Lastly, you guys should be using the reference.bib to cite your sources and have in-text citations. For example, in the paper, the introduction reads:

> broader context to motivate The birth rate is one of the most important determinants of a country’s population growth, potentially impacting policy decisions about the health sys- tem, education, and economy (1). https://www.waldenu.edu/programs/health/resource/why- birth-rates-are-significant-in-health-studies-and-health-science

You should properly put the cite into references.bib and then the paper wouldn't contain of long link URLs.

**Comment by RayanAlim** [comment]
Addressed: Updated ReadME, added LLM usage statement, updated title and used proper citations and references.bib
