### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by jenashahh** [RayanAlim/Birth_Rate_Analysis#5]
**Scripts**
- 00-simulate_data.R seems to be empty, remove if not necessary.
- 03-test_data.R seems to be empty, remove if not necessary.
- 99-replications.R seems to be empty, remove if not necessary.

**Paper**
- Paper seems to be incomplete.

**Overall**
- Great topic and great analysis!

**Comment by RayanAlim** [comment]
Addressed: Updates simulate data files and tests as well as added replication folder with replications.
